=== MartinBronzo/ingswAM2021-Bindi-Borsatto-Bronzo/DevCardConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="DevCardConfig" type="DevCardConfigType"/>
    <xs:complexType name="ResourceType">
        <xs:sequence>
            <xs:element name="Type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="COIN"/>
                        <xs:enumeration value="STONE"/>
                        <xs:enumeration value="SERVANT"/>
                        <xs:enumeration value="FAITHPOINT"/>
                        <xs:enumeration value="SHIELD"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Quantity" type="xs:nonNegativeInteger"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ProductionInputType">
        <xs:sequence>
            <xs:element type="ResourceType" name="Resource" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ProductionOutputType">
        <xs:sequence>
            <xs:element type="ResourceType" name="Resource" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CostType">
        <xs:sequence>
            <xs:element type="ResourceType" name="Resource" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DevCardType">
        <xs:sequence>
            <xs:element name="Level">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="3"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Colour">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="GREEN"/>
                        <xs:enumeration value="BLUE"/>
                        <xs:enumeration value="PURPLE"/>
                        <xs:enumeration value="YELLOW"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="VictoryPoints" type="xs:nonNegativeInteger"/>
            <xs:element type="ProductionInputType" name="ProductionInput"/>
            <xs:element type="ProductionOutputType" name="ProductionOutput"/>
            <xs:element type="CostType" name="Cost"/>
            <xs:element type="xs:string" name="url"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DevCardConfigType">
        <xs:sequence>
            <xs:element type="DevCardType" name="DevCard" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== MartinBronzo/ingswAM2021-Bindi-Borsatto-Bronzo/DevCardConfig.xsd.xml
<DevCardConfig
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="DevCardConfig.xsd">

    <!--DEVCARD-->
    <DevCard>
        <Level>1</Level>
        <Colour>GREEN</Colour>
        <VictoryPoints>1</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>COIN</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionInput>
        <ProductionOutput>
            <Resource>
                <Type>FAITHPOINT</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionOutput>
        <Cost>
            <Resource>
                <Type>SHIELD</Type>
                <Quantity>2</Quantity>
            </Resource>
        </Cost>
        <url>url1</url>
    </DevCard>

    <!--DEVCARD-->
    <DevCard>
        <Level>1</Level>
        <Colour>PURPLE</Colour>
        <VictoryPoints>3</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>COIN</Type>
                <Quantity>2</Quantity>
            </Resource>
        </ProductionInput>
        <ProductionOutput>
            <Resource>
                <Type>SERVANT</Type>
                <Quantity>1</Quantity>
            </Resource>
            <Resource>
                <Type>SHIELD</Type>
                <Quantity>1</Quantity>
            </Resource>
            <Resource>
                <Type>STONE</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionOutput>
        <Cost>
            <Resource>
                <Type>SERVANT</Type>
                <Quantity>3</Quantity>
            </Resource>
        </Cost>
        <url>url2</url>
    </DevCard>

    <!--DEVCARD-->
    <DevCard>
        <Level>1</Level>
        <Colour>BLUE</Colour>
        <VictoryPoints>3</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>STONE</Type>
                <Quantity>2</Quantity>
            </Resource>
        </ProductionInput>
        <ProductionOutput>
            <Resource>
                <Type>COIN</Type>
                <Quantity>1</Quantity>
            </Resource>
            <Resource>
                <Type>SERVANT</Type>
                <Quantity>1</Quantity>
            </Resource>
            <Resource>
                <Type>SHIELD</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionOutput>
        <Cost>
            <Resource>
                <Type>COIN</Type>
                <Quantity>3</Quantity>
            </Resource>
        </Cost>
        <url>url3</url>
    </DevCard>

    <!--DEVCARD-->
    <DevCard>
        <Level>1</Level>
        <Colour>YELLOW</Colour>
        <VictoryPoints>3</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>SHIELD</Type>
                <Quantity>2</Quantity>
            </Resource>
        </ProductionInput>
        <ProductionOutput>
            <Resource>
                <Type>COIN</Type>
                <Quantity>1</Quantity>
            </Resource>
            <Resource>
                <Type>SERVANT</Type>
                <Quantity>1</Quantity>
            </Resource>
            <Resource>
                <Type>STONE</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionOutput>
        <Cost>
            <Resource>
                <Type>STONE</Type>
                <Quantity>3</Quantity>
            </Resource>
        </Cost>
        <url>url4</url>
    </DevCard>

    <!--DEVCARD-->
    <DevCard>
        <Level>1</Level>
        <Colour>GREEN</Colour>
        <VictoryPoints>4</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>STONE</Type>
                <Quantity>1</Quantity>
            </Resource>
            <Resource>
                <Type>SERVANT</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionInput>
        <ProductionOutput>
            <Resource>
                <Type>COIN</Type>
                <Quantity>2</Quantity>
            </Resource>
            <Resource>
                <Type>FAITHPOINT</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionOutput>
        <Cost>
            <Resource>
                <Type>SHIELD</Type>
                <Quantity>2</Quantity>
            </Resource>
            <Resource>
                <Type>COIN</Type>
                <Quantity>2</Quantity>
            </Resource>
        </Cost>
        <url>url2</url>
    </DevCard>

    <!--DEVCARD-->
    <DevCard>
        <Level>1</Level>
        <Colour>PURPLE</Colour>
        <VictoryPoints>4</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>COIN</Type>
                <Quantity>1</Quantity>
            </Resource>
            <Resource>
                <Type>SHIELD</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionInput>
        <ProductionOutput>
            <Resource>
                <Type>STONE</Type>
                <Quantity>2</Quantity>
            </Resource>
            <Resource>
                <Type>FAITHPOINT</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionOutput>
        <Cost>
            <Resource>
                <Type>SERVANT</Type>
                <Quantity>2</Quantity>
            </Resource>
            <Resource>
                <Type>STONE</Type>
                <Quantity>2</Quantity>
            </Resource>
        </Cost>
        <url>url2</url>
    </DevCard>

    <!--DEVCARD-->
    <DevCard>
        <Level>1</Level>
        <Colour>BLUE</Colour>
        <VictoryPoints>4</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>SHIELD</Type>
                <Quantity>1</Quantity>
            </Resource>
            <Resource>
                <Type>STONE</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionInput>
        <ProductionOutput>
            <Resource>
                <Type>SERVANT</Type>
                <Quantity>2</Quantity>
            </Resource>
            <Resource>
                <Type>FAITHPOINT</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionOutput>
        <Cost>
            <Resource>
                <Type>COIN</Type>
                <Quantity>2</Quantity>
            </Resource>
            <Resource>
                <Type>SERVANT</Type>
                <Quantity>2</Quantity>
            </Resource>
        </Cost>
        <url>url2</url>
    </DevCard>

    <!--DEVCARD-->
    <DevCard>
        <Level>1</Level>
        <Colour>YELLOW</Colour>
        <VictoryPoints>4</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>COIN</Type>
                <Quantity>1</Quantity>
            </Resource>
            <Resource>
                <Type>SERVANT</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionInput>
        <ProductionOutput>
            <Resource>
                <Type>SHIELD</Type>
                <Quantity>2</Quantity>
            </Resource>
            <Resource>
                <Type>FAITHPOINT</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionOutput>
        <Cost>
            <Resource>
                <Type>STONE</Type>
                <Quantity>2</Quantity>
            </Resource>
            <Resource>
                <Type>SHIELD</Type>
                <Quantity>2</Quantity>
            </Resource>
        </Cost>
        <url>url2</url>
    </DevCard>

    <!--DEVCARD-->
    <DevCard>
        <Level>2</Level>
        <Colour>GREEN</Colour>
        <VictoryPoints>5</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>STONE</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionInput>
        <ProductionOutput>
            <Resource>
                <Type>FAITHPOINT</Type>
                <Quantity>2</Quantity>
            </Resource>
        </ProductionOutput>
        <Cost>
            <Resource>
                <Type>SHIELD</Type>
                <Quantity>4</Quantity>
            </Resource>
        </Cost>
        <url>url2</url>
    </DevCard>

    <!--DEVCARD-->
    <DevCard>
        <Level>2</Level>
        <Colour>PURPLE</Colour>
        <VictoryPoints>5</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>COIN</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionInput>
        <ProductionOutput>
            <Resource>
                <Type>FAITHPOINT</Type>
                <Quantity>2</Quantity>
            </Resource>
        </ProductionOutput>
        <Cost>
            <Resource>
                <Type>SERVANT</Type>
                <Quantity>4</Quantity>
            </Resource>
        </Cost>
        <url>url2</url>
    </DevCard>

    <!--DEVCARD-->
    <DevCard>
        <Level>2</Level>
        <Colour>BLUE</Colour>
        <VictoryPoints>5</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>SERVANT</Type>
                <Quantity>1</Quantity>
            </Resource>
        </ProductionInput>
        <ProductionOutput>
            <Resource>
                <Type>FAITHPOINT</Type>
                <Quantity>2</Quantity>
            </Resource>
        </ProductionOutput>
        <Cost>
            <Resource>
                <Type>COIN</Type>
                <Quantity>4</Quantity>
            </Resource>
        </Cost>
        <url>url2</url>
    </DevCard>

    <!--DEVCARD-->
    <DevCard>
        <Level>1</Level>
        <Colour>PURPLE</Colour>
        <VictoryPoints>1</VictoryPoints>
        <ProductionInput>
            <Resource>
                <Type>STONE</Type>
