=== MartinBronzo/ingswAM2021-Bindi-Borsatto-Bronzo/MarketConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="MarketConfig" type="MarketConfigType"/>
    <xs:complexType name="marbleType">
        <xs:sequence>
            <xs:element name="Type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="WHITEMARBLE"/>
                        <xs:enumeration value="BLUEMARBLE"/>
                        <xs:enumeration value="GREYMARBLE"/>
                        <xs:enumeration value="YELLOWMARBLE"/>
                        <xs:enumeration value="PURPLEMARBLE"/>
                        <xs:enumeration value="REDMARBLE"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="quantity">
                <xs:simpleType>
                    <xs:restriction base="xs:nonNegativeInteger">
                        <xs:maxInclusive value="13"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MarketConfigType">
        <xs:sequence>
            <xs:element type="marbleType" name="marble" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== MartinBronzo/ingswAM2021-Bindi-Borsatto-Bronzo/src/main/resources/XMLs/MarketConfig.xsd.xml
<MarketConfig
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="MarketConfig.xsd">
    <marble>
        <Type>WHITEMARBLE</Type>
        <quantity>4</quantity>
    </marble>
    <marble>
        <Type>BLUEMARBLE</Type>
        <quantity>2</quantity>
    </marble>
    <marble>
        <Type>GREYMARBLE</Type>
        <quantity>2</quantity>
    </marble>
    <marble>
        <Type>YELLOWMARBLE</Type>
        <quantity>2</quantity>
    </marble>
    <marble>
        <Type>PURPLEMARBLE</Type>
        <quantity>2</quantity>
    </marble>
    <marble>
        <Type>REDMARBLE</Type>
        <quantity>1</quantity>
    </marble>
</MarketConfig>
